server:
  port: 8081
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            rule-type: flow
    
